#!/usr/bin/osascript

tell application "Terminal" to activate
tell application "System Events" to tell process "Terminal" to keystroke "c" using control down
delay 0.5

tell application "Terminal" to do script "node ./index.js" in first window whose name starts with "server"
delay 1

tell application "Yandex"
    activate

    -- switch to "localhost" tab
    set i to 0
    repeat with t in (tabs of (first window))
        set i to i + 1
        if title of t is "localhost" then
            set (active tab index of (first window)) to i
        end if
    end repeat
end tell

tell application "System Events" to tell process "Terminal" to keystroke "r" using command down
delay 0.5

tell application "Terminal" to activate
